version: '3.4'

networks:
  menu:
  gateway:
  marketing:


services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: MicroServices/Gateways/ApiGateway/Dockerfile
    networks:
       - gateway
    depends_on:
      - menu.api
      - marketing.api 
    ports:
      - "5000:8080"
      - "5001:8081"

  menu.api:
    image: ${DOCKER_REGISTRY-}menuapi
    build:
      context: .
      dockerfile: MicroServices/APIs/Menu/Menu.API/Dockerfile
    networks:
      - menu
      - gateway 
    depends_on:
      - menu.db
    environment:
      - DB_HOST=menu.db
      - DB_DATABASE=MenuDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!1

  menu.db:
    container_name: menudb
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - menu
    ports:
      - "7000:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd123!!1
      - MSSQL_PID=Developer

  marketing.api:
    container_name: marketing.api
    build:
      context: .
      dockerfile: MicroServices/APIs/Marketing/Marketing.API/Dockerfile
    networks:
      - gateway
      - marketing
    depends_on:
      - marketing.db
    environment:
      - DB_HOST=marketing.db
      - DB_DATABASE=MarketingDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!1
  
  marketing.db:
    container_name: marketingdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - marketing
    ports:
        - "7001:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd123!!1
      - MSSQL_PID=Developer
